Update support and advice
DFE-Digital/find-teacher-training-prototype pull request #155
Opened 2022-11-16 15:58 UTC by Kateharries

I have updated the content in the support and advice section. I removed the section about different ways to train and improved the first paragraph to make the role of TTAs more specific.

2022-11-16 16:22 UTC, Kateharries commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review 'Advice from GIT' and links between Find and GIT](https://trello.com/c/g02VlU3W/672-review-advice-from-git-and-links-between-find-and-git)

2022-11-17 09:34 UTC, simonwhatley requested changes

2022-11-17 09:34 UTC, simonwhatley commented on app/views/course/sections/support-and-advice.njk
> +    experience, and find events where you can speak to training providers and teachers.</p>
> They‘re all **experienced** teachers who can give you **experience**, and find events where you can speak to training providers and teachers.

You've repeated the word 'experience', with the second instance not making much sense. Could the second instance be replaced with 'advice'?

> They‘re all experienced teachers who can give you **advice**, and **help you** find events where you can speak to training providers and teachers.

(emphasis mine)

2022-11-17 16:01 UTC, simonwhatley approved these changes

2022-11-17 16:02 UTC, merged