Events content on Find service start page
DFE-Digital/find-teacher-training-prototype pull request #187
Opened 2023-02-14 14:00 UTC by Kateharries

2023-02-14 14:33 UTC, simonwhatley requested changes

2023-02-14 14:33 UTC, simonwhatley commented on app/views/results/_promoted-link.njk
> +  <a class="govuk-link" href="https://getintoteaching.education.gov.uk/events/about-get-into-teaching-events?utm_source=find-postgraduate-teacher-training.service.gov.uk&utm_medium=referral&utm_campa
No need to add Google tags to the prototype code.

```suggestion
  <a class="govuk-link" href="https://getintoteaching.education.gov.uk/events/about-get-into-teaching-events?utm_source=find-postgraduate-teacher-training.service.gov.uk">Talk to teacher training providers at an event near you</a>.
```

2023-02-14 14:33 UTC, simonwhatley commented on app/views/search/index.njk
> +
I think you need to separate the content from the form. For example:

```
## Meet local teacher training providers

Meet local teacher training providers at a [Get Into teaching event](url) where you can:

- get advice on your application
- talk to existing teachers
- connect with people like you who are interested in teaching
```

2023-02-14 14:34 UTC, simonwhatley commented on app/views/search/index.njk
> +      <p class="govuk-body"><a class="govuk-link" href="https://getintoteaching.education.gov.uk/events/about-get-into-teaching-events?utm_source=find-postgraduate-teacher-training.service.gov.uk&utm
No need to add Google tags to the prototype code

```suggestion
      <p class="govuk-body"><a class="govuk-link" href="https://getintoteaching.education.gov.uk/events/about-get-into-teaching-events?utm_source=find-postgraduate-teacher-training.service.gov.uk">Meet local teacher training providers at a Get Into teaching event</a> where you can: </p>
```

2023-02-14 14:35 UTC, simonwhatley commented on app/views/search/index.njk
> +        </p>
```suggestion
      </ul>
```

2023-02-14 17:19 UTC, Kateharries commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add events content to first page on Find](https://trello.com/c/OwKID0wI/1030-add-events-content-to-first-page-on-find)

2023-02-15 10:40 UTC, simonwhatley approved these changes

2023-02-15 10:45 UTC, merged